id: fc59237162604cc599e9f1b7c64399f3
initial_creation_type: ocr
source_metadata:
  volumes:
    32ed64d404884950a15c963360a4683a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
